# Generated by Django 4.2.5 on 2023-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_documents_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="document",
            field=models.FileField(upload_to=""),
        ),
    ]
