# Generated by Django 4.2.5 on 2023-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_documents_created_at_documents_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
